### ISSUE TITLE
bug(python): `where` clause ignored in FTS when a scalar index exists

### ISSUE THREAD

**Issue by mykolaskrynnyk** [lancedb/lancedb#1656]
### LanceDB version

0.13.0

### What happened?

When performing a (lance) full-text search, a `where` clause works as expected on a field that has not been indexed but is ignored if a scalar index for the field exists.

Relatedly, the [documentation](https://lancedb.github.io/lancedb/fts/#filtering) states that "the LanceDB full text search feature supports post-filtering, meaning filters are applied on top of the full text search results.".  But in fact, it's the `prefilter=True` setting that seems to work as expected. See examples below for details.

## Set-up for Full-text Search

```python
import lancedb

uri = "data/sample-lancedb"
db = lancedb.connect(uri)

table = db.create_table(
    "my_table",
    data=[
        {"vector": [3.1, 4.1], "text": "Frodo was a happy puppy", "sentiment": "positive"},
        {"vector": [3.2, 4.3], "text": "Frodo was a very happy puppy", "sentiment": "positive"},
        {"vector": [3.4, 4.0], "text": "Frodo was a puppy", "sentiment": "neutral"},
        {"vector": [5.9, 26.5], "text": "There are several kittens playing", "sentiment": "neutral"},
    ],
)

# passing `use_tantivy=False` to use lance FTS index
# `use_tantivy=True` by default
table.create_fts_index("text", use_tantivy=False)
```

## Example 1: No Filters

FTS without filters works as expected.

### Input

```python
table.search("puppy").select(["text", "sentiment"]).to_list()
```

### Output

```json
[
  {
    "text": "Frodo was a puppy",
    "sentiment": "neutral",
    "_score": 0.38845789432525635
  },
  {
    "text": "Frodo was a happy puppy",
    "sentiment": "positive",
    "_score": 0.3566749691963196
  },
  {
    "text": "Frodo was a very happy puppy",
    "sentiment": "positive",
    "_score": 0.3296995460987091
  }
]
```

## Example 2: Filter by an Unindexed Field

FTS with a filter on an unindexed field also works as expected.

### Input

```python
table.search("puppy").where("sentiment='positive'").select(["text", "sentiment"]).to_list()
```

### Output

```json
[
  {
    "text": "Frodo was a happy puppy",
    "sentiment": "positive",
    "_score": 0.3566749691963196
  },
  {
    "text": "Frodo was a very happy puppy",
    "sentiment": "positive",
    "_score": 0.3296995460987091
  }
]
```

## Example 3: Filter by an Indexed Field (default)

If a scalar index exists, the search breaks. This is quite unexpected as there is only one text index, so
the engine should be able to figure out which one to use for FTS.

### Input

```python
# create a scalar index for a field
table.create_scalar_index("sentiment", replace=True)
# this raises an error
table.search("puppy").where("sentiment='positive'").select(["text", "sentiment"]).to_list()
```

### Output

```python
ValueError: LanceError(IO): Full text search supports only one column right now, but got 2 columns, /Users/runner/work/lance/lance/rust/lance/src/dataset/scanner.rs:1147:17
```

## Example 4: Filter by an Indexed Field (`fts_columns`)

Specifying the column for FTS resolves the value error and the search works but the results are incorrect. The `where` clause is ignored.

### Input

```python
table.create_scalar_index("sentiment", replace=True)
table.search("puppy", fts_columns="text").where("sentiment='positive'").limit(10).select(["text", "sentiment"]).to_list()
```

### Output

```json
[
  {
    "text": "Frodo was a puppy",
    "sentiment": "neutral",
    "_score": 0.38845789432525635
  },
  {
    "text": "Frodo was a happy puppy",
    "sentiment": "positive",
    "_score": 0.3566749691963196
  },
  {
    "text": "Frodo was a very happy puppy",
    "sentiment": "positive",
    "_score": 0.3296995460987091
  }
]
```

## Example 5: Filter by an Indexed Field (`fts_columns` and `prefilter`)

Specifying the column for FTS and setting `prefilter` to `True` produces the desired results despite the documentation stating that FTS support post-filtering.

### Input

```python
table.search("puppy", fts_columns="text").where("sentiment='positive'", prefilter=True).select(["text", "sentiment"]).to_list()
```

### Output

```json
[
  {
    "text": "Frodo was a happy puppy",
    "sentiment": "positive",
    "_score": 0.3566749691963196
  },
  {
    "text": "Frodo was a very happy puppy",
    "sentiment": "positive",
    "_score": 0.3296995460987091
  }
]
```

**Comment by westonpace** [comment]
This may have been fixed by https://github.com/lancedb/lance/pull/2875 (not yet released)

**Comment by mykolaskrynnyk** [comment]
@westonpace , just to follow up on the original issue. It turns out that Example 5 above does not actually fix the problem. The results are correct in that specific case by chance. If you shuffle the rows in the original data like so:

```python
table = db.create_table(
    "my_table",
    data=[
        {"vector": [3.4, 4.0], "text": "Frodo was a puppy", "sentiment": "neutral"},
        {"vector": [3.1, 4.1], "text": "Frodo was a happy puppy", "sentiment": "positive"},
        {"vector": [3.2, 4.3], "text": "Frodo was a very happy puppy", "sentiment": "positive"},
        {"vector": [5.9, 26.5], "text": "There are several kittens playing", "sentiment": "neutral"},
    ],
)
```

And rerun the code from Example 5, the output will include an incorrect match:

### Input

```python
table.search("puppy", fts_columns="text").where("sentiment='positive'", prefilter=True).select(["text", "sentiment"]).to_list()
```

### Output

```json
[
  {
    "_score": 0.38845789432525635,
    "sentiment": "neutral",
    "text": "Frodo was a puppy"
  },
  {
    "_score": 0.3566749691963196,
    "sentiment": "positive",
    "text": "Frodo was a happy puppy"
  },
  {
    "_score": 0.3296995460987091,
    "sentiment": "positive",
    "text": "Frodo was a very happy puppy"
  }
]
```

## An Erroneous Extra Match

In fact, it seems that there is some index/offset issue in the underlying query as it returns the first (erroneous) entry when no results should be returned.

### Input

```python
table.search("puppy", fts_columns="text").where("sentiment='negative'", prefilter=True).select(["text", "sentiment"]).to_list()
```

### Output

```json
[
  {
    "text": "Frodo was a puppy",
    "sentiment": "neutral",
    "_score": 0.38845789432525635
  }
]
```

### Input

```python
table.search("kittens", fts_columns="text").where("sentiment='negative'", prefilter=True).select(["text", "sentiment"]).to_list()
```

### Output

```json
[
  {
    "text": "There are several kittens playing",
    "sentiment": "neutral",
    "_score": 1.2039728164672852
  }
]
```

Since this seems to affect only indexed fields, I'll check if the issue is still there once the upstream changes from lance are propagated.

**Comment by westonpace** [comment]
I've confirmed that these issues still exist in the latest version of lancedb.  I'm going to investigate further and will update soon.

**Comment by westonpace** [comment]
Thanks for the detailed report and reproduction!

I found three issues:

 * All string columns with any kind of scalar index (not just FTS index) were being considered in the "automatically detect which column to apply to FTS search".  This will be fixed in https://github.com/lancedb/lance/pull/2931 and was causing your example 3 to fail.
 * If a filter could be satisfied by a scalar index then it wasn't getting applied in a post-filtering situation.  This will also be fixed by https://github.com/lancedb/lance/pull/2931.  This is what was causing your example 4 to fail.
 * We do seem to be including some false positives in the prefilter / FTS scenario.  I've filed https://github.com/lancedb/lance/issues/2930 to let people more knowledgeable in FTS take a look.
